# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: efisef/circle-base
      - image: redis

    working_directory: ~/ensorcel

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - add_ssh_keys
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - run: echo "127.0.0.1 redis" >> /etc/hosts

      # run tests!
      - run: lein test
      - run: LC_ALL=C lein doo phantom test once

  deploy:
    docker:
      - image: efisef/circle-base
    working_directory: ~/ensorcel
    steps:
      - checkout
      - run: echo "Deploying goes here!"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
